name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

defaults:
    run:
        shell: bash

permissions:
  contents: write

jobs:
  quarto:
    name: quarto_render
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rmarkdown
            tidyverse
            kofdata
          install-quarto: 'true'
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: index.qmd
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
            # token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
            folder: '.'
            clean: true
